name: "Danger Kotlin"
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/kotlin@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
