name: "Danger Kotlin"
on: [pull_request]

jobs:
  danger-kotlin:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/kotlin@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  danger-swift:
    runs-on: ubuntu-latest
    name: "Run Danger Swift"
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/swift@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
